# Generated by Django 4.1.7 on 2023-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_detail", models.TextField()),
                (
                    "requirements",
                    models.CharField(
                        choices=[
                            ("full band", "full band"),
                            ("two piece", "two piece"),
                            ("single artist", "single artist"),
                            ("acoustic", "acoustic"),
                        ],
                        max_length=200,
                    ),
                ),
                ("payment", models.CharField(max_length=200)),
            ],
        ),
    ]
