# Generated by Django 4.1.7 on 2023-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='requirements',
            field=models.CharField(blank=True, choices=[('full band', 'full band'), ('two piece', 'two piece'), ('single artist', 'single artist'), ('acoustic', 'acoustic')], max_length=200, null=True),
        ),
    ]
