# Generated by Django 4.1.7 on 2023-03-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventpost_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPost',
        ),
    ]
