# Generated by Django 4.1.7 on 2023-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_delete_eventpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
