# Generated by Django 4.1.7 on 2023-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="artist_type_band",
            field=models.CharField(
                blank=True,
                choices=[("a", "a"), ("b", "b"), ("c", "c")],
                max_length=200,
                null=True,
            ),
        ),
    ]
